[tools]
rust = "latest"

[tasks.dev]
tools = { "watchexec" = "latest", "bun" = "latest" }
run = ["watchexec -c -r -w public -w src 'mise build && bunx vite dist/'"]

[tasks]
build = ["mkdir -p dist", "cp -r public/** dist", "cargo run -r"]
