[tools]
rust = "latest"

[tasks.dev]
tools = { node = "latest", "npm:vite" = "latest", watchexec = "latest" }
depends = ["build"]
run = ["vite dist"]
sources = ["public/**/*", "src/**/*"]

[tasks]
build = ["mkdir -p dist", "cp -r public/** dist", "cargo run -r"]
