[tools]
rust = "latest"

[tasks.dev]
tools = { node = "latest", "npm:vite" = "latest", watchexec = "latest" }
depends = ["build"]
run = ["cargo run -r", "vite dist"]
sources = ["public/**/*", "src/**/*"]

[tasks]
build = ["cargo run -r"]
