name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request
        uses: changesets/action@main
        with:
          publish: npx changeset tag
          commit: Update version
          title: "[CI] Update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
